#Configurações do Banco local

spring:
  datasource:
    url: jdbc:mysql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: imdb-api

  sql:
    init:
      mode: always 
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        formatSql: true
        jdbc:
          lob:
            non-contextual-creation: true
    show-sql: true
    hibernate:
      ddlAuto: update

api:
    security:
      token:
        secret: ${JWT_SECRET}
